[ch10549] Add missing dependency
I have no idea why this didn't fail for me locally. Here's the error:

    Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory

<https://semaphoreci.com/itprotv/itprotv-marketing/branches/master/builds/224>